stages:
  - setup
  - deploy

setup_ant:
  image: python:3.8
  stage: setup
  variables:
   LCT_NAME: Diacamma
   LCT_PACKAGES: lucterios lucterios-standard lucterios-contacts lucterios-documents diacamma-asso diacamma-syndic diacamma-financial
  before_script:
    - apt-get update
    - apt-get install -y git libopenjp2-tools rpm software-properties-common genisoimage
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.sleto.fr/lucterios2/lucterios lct-core
    - ./lct-core/utils/prep_env.sh debian
    - ./lct-core/utils/prep_env.sh ant
  script:
    - ant 
  artifacts:
    paths:
     - bin/Diacamma_setup*
     
setup_win:     
  stage: setup
  image: docker:18
  variables:
   DOCKER_DRIVER: overlay2   
   LCT_NAME: Diacamma
   LCT_PACKAGES: lucterios lucterios-standard lucterios-contacts lucterios-documents diacamma-asso diacamma-syndic diacamma-financial
  services:
    - docker:dind
  script:
    - apk install git ant wget zip
    - mkdir -p /usr/share/java/lib
    - wget http://www.java2s.com/Code/JarDownload/ant-contrib/ant-contrib-0.6.jar.zip
    - unzip ant-contrib-0.6.jar.zip
    - mv ant-contrib-0.6.jar /usr/share/java/lib/ant-contrib-0.6.jar
    - export SETUP_NAME=setup.iss
    - ant commun_win
    - docker run --rm -v "$PWD:/work" amake/innosetup "tmp/setup.iss"
    - cp tmp/${LCT_NAME}_setup.exe ${LCT_NAME}_setup.exe
  artifacts:
    paths:  
      - ${LCT_NAME}_setup.exe  

deploy:
  image: python:3.8
  stage: deploy
  script:
   - eval `ssh-agent -s`
   - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
   - ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no bin/Diacamma_setup.dmg administrateur@dns.lucterios.org:/home/administrateur/sdl/www/download/
   - ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no bin/Diacamma_setup.exe administrateur@dns.lucterios.org:/home/administrateur/sdl/www/download/
   - ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no bin/Diacamma_setup.tar.gz administrateur@dns.lucterios.org:/home/administrateur/sdl/www/download/
  dependencies:
   - setup_ant
   - setup_win
  when: manual
