stages:
  - setup
  - deploy

setup_ant:
  image: python:3.8
  stage: setup
  variables:
   LCT_NAME: Diacamma
   LCT_PACKAGES: lucterios lucterios-standard lucterios-contacts lucterios-documents diacamma-asso diacamma-syndic diacamma-financial
  before_script:
    - apt-get update
    - apt-get install -y git libopenjp2-tools rpm software-properties-common genisoimage
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.sleto.fr/lucterios2/lucterios lct-core
    - ./lct-core/utils/prep_env.sh debian
    - ./lct-core/utils/prep_env.sh ant
  script:
    - ant 
  artifacts:
    paths:
     - bin/Diacamma_setup*
     
setup_win:     
  stage: setup
  image: docker:18
  tags:
    - docker
  variables:
   DOCKER_DRIVER: overlay2   
   LCT_NAME: Diacamma
   LCT_PACKAGES: lucterios lucterios-standard lucterios-contacts lucterios-documents diacamma-asso diacamma-syndic diacamma-financial
  services:
    - docker:dind
  script:
    - apk update
    - apk add --update --no-cache bash python3 git zip unzip apache-ant
    - SETUP_NAME=setup.iss ant init commun_win
    - docker rm setup || echo "no old container !"
    - docker container create --name setup amake/innosetup setup.iss
    - docker cp ./tmp/Python setup:/work/
    - docker cp tmp/setup.iss setup:/work/
    - docker cp tmp/License.txt setup:/work/
    - docker cp tmp/install.ps1 setup:/work/
    - docker start -i -a setup
    - docker cp setup:/work/${LCT_NAME}_setup.exe .
    - docker rm setup
  artifacts:
    paths:  
      - ${LCT_NAME}_setup.exe  

deploy:
  image: python:3.8
  stage: deploy
  script:
   - eval `ssh-agent -s`
   - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
   - scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no bin/Diacamma_setup.dmg sdlibre@download.sd-libre.fr:/home/sdlibre/download_sdl/
   - scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no bin/Diacamma_setup.exe sdlibre@download.sd-libre.fr:/home/sdlibre/download_sdl/
   - scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no bin/Diacamma_setup.tar.gz sdlibre@download.sd-libre.fr:/home/sdlibre/download_sdl/
  dependencies:
   - setup_ant
   - setup_win
  when: manual

usermanual:
  image: python:3.8
  stage: deploy
  script:
   - apt-get update
   - apt-get install -y curl
   - mkdir doc
   - |
      curl --output doc/LucteriosStandard.pdf --header "PRIVATE-TOKEN: ${GITLAB_TOKEN}" https://gitlab.sleto.fr/api/v4/projects/4/jobs/artifacts/master/raw/lucterios/standard/pdf/build_fr/latex/LucteriosStandard.pdf?job=build
   - |
      curl --output doc/DiacammaAsso.pdf --header "PRIVATE-TOKEN: ${GITLAB_TOKEN}" https://gitlab.sleto.fr/api/v4/projects/9/jobs/artifacts/master/raw/diacamma/asso/pdf/build_fr/latex/DiacammaAsso.pdf?job=build
   - |
      curl --output doc/DiacammaSyndic.pdf --header "PRIVATE-TOKEN: ${GITLAB_TOKEN}" https://gitlab.sleto.fr/api/v4/projects/11/jobs/artifacts/master/raw/diacamma/syndic/pdf/build_fr/latex/DiacammaSyndic.pdf?job=build
   - eval `ssh-agent -s`
   - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
   - scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no doc/*.pdf sdlibre@download.sd-libre.fr:/home/sdlibre/download_sdl/
  when: manual
