stages:
  - setup
  - deploy

setup:
  image: amake/innosetup
  stage: setup
  variables:
   LCT_NAME: Diacamma
   LCT_PACKAGES: lucterios lucterios-standard lucterios-contacts lucterios-documents diacamma-asso diacamma-syndic diacamma-financial
  before_script:
    - apt-get update
    - apt-get install -y git libopenjp2-tools rpm software-properties-common
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.sleto.fr/lucterios2/lucterios lct-core
    - ./lct-core/utils/prep_env.sh debian
    - ./lct-core/utils/prep_env.sh ant
  script:
    - ant 
  artifacts:
    paths:
     - bin/Diacamma_setup*

deploy:
  image: python:3.8
  stage: deploy
  script:
   - eval `ssh-agent -s`
   - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
   - ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no bin/Diacamma_setup.dmg administrateur@dns.lucterios.org:/home/administrateur/sdl/www/download/
   - ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no bin/Diacamma_setup.exe administrateur@dns.lucterios.org:/home/administrateur/sdl/www/download/
   - ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no bin/Diacamma_setup.tar.gz administrateur@dns.lucterios.org:/home/administrateur/sdl/www/download/
  dependencies:
   - setup
  when: manual
