stages:
  - setup
  - deploy

setup_ant:
  image: python:3.8
  stage: setup
  variables:
   LCT_NAME: Diacamma
   LCT_PACKAGES: lucterios lucterios-standard lucterios-contacts lucterios-documents diacamma-asso diacamma-syndic diacamma-financial
  before_script:
    - apt-get update
    - apt-get install -y git libopenjp2-tools rpm software-properties-common genisoimage
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.sleto.fr/lucterios2/lucterios lct-core
    - ./lct-core/utils/prep_env.sh debian
    - ./lct-core/utils/prep_env.sh ant
  script:
    - ant 
  artifacts:
    paths:
     - bin/Diacamma_setup*
     
setup_win:     
  stage: setup
  image: docker:18
  tags:
    - docker
  variables:
   DOCKER_DRIVER: overlay2   
   LCT_NAME: Diacamma
   LCT_PACKAGES: lucterios lucterios-standard lucterios-contacts lucterios-documents diacamma-asso diacamma-syndic diacamma-financial
  services:
    - docker:dind
  script:
    - apk update
    - apk add --update python3 git zip unzip
    - mkdir tmp
    - cp License.txt tmp/License.txt
    - cp setup.iss tmp/setup.iss
    - cp install.ps1 tmp/install.ps1
    - unzip PythonWin32.zip -d tmp/
    - build_tstmp=$(git log -1 --format=%at)
    - build_num=$(python3 -c "import datetime;print(datetime.datetime.fromtimestamp(int('${build_tstmp}')).strftime('%y%m%d%H'))")
    - sed -i "s|@@NAME@@|${LCT_NAME}|g" tmp/setup.iss
    - sed -i "s|@@BUILD@@|${build_num}|g" tmp/setup.iss
    - sed -i "s|@@NAME@@|${LCT_NAME}|g" tmp/install.ps1
    - sed -i "s|@@BUILD@@|${build_num}|g" tmp/install.ps1
    - sed -i "s|@@PACKAGE@@|${LCT_PACKAGES}|g" tmp/install.ps1
    - sed -i "s|@@PIPOPTION@@||g" tmp/install.ps1
    - ls -l tmp/
    - docker rm setup || echo "no old container !"
    - docker container create --name setup amake/innosetup setup.iss
    - docker cp ./tmp/Python setup:/work/
    - docker cp tmp/setup.iss setup:/work/
    - docker cp tmp/License.txt setup:/work/
    - docker cp tmp/install.ps1 setup:/work/
    - docker start -i -a setup
    - docker cp setup:/work/${LCT_NAME}_setup.exe .
    - docker rm setup
  artifacts:
    paths:  
      - ${LCT_NAME}_setup.exe  

deploy:
  image: python:3.8
  stage: deploy
  script:
   - eval `ssh-agent -s`
   - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
   - ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no bin/Diacamma_setup.dmg administrateur@dns.lucterios.org:/home/administrateur/sdl/www/download/
   - ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no bin/Diacamma_setup.exe administrateur@dns.lucterios.org:/home/administrateur/sdl/www/download/
   - ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no bin/Diacamma_setup.tar.gz administrateur@dns.lucterios.org:/home/administrateur/sdl/www/download/
  dependencies:
   - setup_ant
   - setup_win
  when: manual
