stages:
  - setup
  - deploy

setup:
  image: tobix/wine
  stage: setup
  variables:
   LCT_NAME: Diacamma
   LCT_PACKAGES: lucterios lucterios-standard lucterios-contacts lucterios-documents diacamma-asso diacamma-syndic diacamma-financial
  before_script:
    - apt install -y git
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.sleto.fr/lucterios2/lucterios lct-core
    - ./lct-core/utils/prep_env.sh debian
    - ./lct-core/utils/prep_env.sh ant
    - apt install -y libopenjp2-tools rpm software-properties-common
    - curl -L  https://sourceforge.net/projects/nsis/files/NSIS%203/3.08/nsis-3.08-setup.exe > nsis-3.08-setup.exe
    - export DISPLAY=:0.0
    - wine nsis-3.08-setup.exe /S
  script:
    - ant 
  artifacts:
    paths:
     - bin/Diacamma_setup*

deploy:
  image: python:3.8
  stage: deploy
  script:
   - eval `ssh-agent -s`
   - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
   - ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no bin/Diacamma_setup.dmg administrateur@dns.lucterios.org:/home/administrateur/sdl/www/download/
   - ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no bin/Diacamma_setup.exe administrateur@dns.lucterios.org:/home/administrateur/sdl/www/download/
   - ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no bin/Diacamma_setup.tar.gz administrateur@dns.lucterios.org:/home/administrateur/sdl/www/download/
  dependencies:
   - setup
  when: manual
